### ISSUE TITLE
How can I get mission-definitions?

### ISSUE THREAD

**Issue by musnows** [techchrism/valorant-api-docs#12]
I get my contract from `url` down below
```python
async def fetch_player_contract(u):
    #url="https://pd.ap.a.pvp.net/contract-definitions/v2/definitions/story"
    url=f"https://pd.ap.a.pvp.net/contracts/v1/contracts/"+u['auth_user_id']
    headers = {
        "Content-Type": "application/json",
        "X-Riot-Entitlements-JWT": u['entitlements_token'],
        "Authorization": "Bearer " + u['access_token'],
        "X-Riot-ClientPlatform" : "ew0KCSJwbGF0Zm9ybVR5cGUiOiAiUEMiLA0KCSJwbGF0Zm9ybU9TIjogIldpbmRvd3MiLA0KCSJwbGF0Zm9ybU9TVmVyc2lvbiI6ICIxMC4wLjE5MDQyLjEuMjU2LjY0Yml0IiwNCgkicGxhdGZvcm1DaGlwc2V0IjogIlVua25vd24iDQp9",
        "X-Riot-ClientVersion": "release-05.03-shipping-8-745499"
    }
    async with aiohttp.ClientSession() as session:
        async with session.get(url, headers=headers) as response:
            res = json.loads(await response.text())

    return res
```
it also returns `mission_id` in the end,but I can't find definitions of mission ID
```python
    "Missions": [
        {
            "ID": "75da2732-44ec-80f2-9de8-349da322f634",
            "Objectives": {
                "16af3bdf-c353-4c8c-a47c-b4eeac154eaf": 4
            },
            "Complete": False,
            "ExpirationTime": "2022-08-24T03:00:00Z"
        },
        {
            "ID": "4ef22966-46ac-0fc3-e300-d1a53b669e12",
            "Objectives": {
                "91952692-4345-8bc1-6f1c-2dad7e14109f": 176
            },
            "Complete": False,
            "ExpirationTime": "2022-08-24T03:00:00Z"
        },
        {
            "ID": "c90f3728-447d-ffa5-27a4-6c87fd89f9ce",
            "Objectives": {
                "a617b28c-4ad2-04f6-736e-2eb01a903417": 20
            },
            "Complete": True,
            "ExpirationTime": "2022-08-24T03:00:00Z"
        },
        {
            "ID": "0f33dad7-4e68-398d-35cc-b5a5b1503050",
            "Objectives": {
                "f5d56aa6-4337-2c1c-3cb9-47b7ce9e6304": 0
            },
            "Complete": False,
            "ExpirationTime": "2022-08-23T20:00:00Z"
        },
        {
            "ID": "8f183032-4ba1-b6a2-0574-e0ab6098a08f",
            "Objectives": {
                "c807ef27-420a-69f2-3c0f-31bf8922ba6f": 0
            },
            "Complete": False,
            "ExpirationTime": "2022-08-23T20:00:00Z"
        }
    ],
    "MissionMetadata": {
        "NPECompleted": True,
        "WeeklyCheckpoint": "2022-07-11T13:00:00Z"
    }
}
```

**Comment by musnows** [comment]
I also like to ask how to use [Riot Auth/POST Auth Cookies](https://github.com/techchrism/valorant-api-docs/blob/trunk/docs/Riot%20Auth/POST%20Auth%20Cookies.md) and [GET Cookie Reauth](https://github.com/techchrism/valorant-api-docs/blob/trunk/docs/Riot%20Auth/GET%20Cookie%20Reauth.md)? Now I just use `account/passwd` to get auth-token,that's not good for users.

Is `id_token` a variable？I try the cookies found in [How-to-get-your-Riot-cookies](https://github.com/giorgi-o/SkinPeek/wiki/How-to-get-your-Riot-cookies) to replace `id_token`,it return `status-200` but I can't find auth-token.
```
{"client_id":"play-valorant-web-prod","nonce":"1","redirect_uri":"https://playvalorant.com/opt_in","response_type":"token id_token"}
```

**Comment by techchrism** [comment]
Honestly, I'm not sure where you can find mission definitions. I haven't worked with those before.

For the cookie reauth, there are no placeholders in the url, just do a GET request using the cookies obtained from the initial auth.

**Comment by musnows** [comment]
> Honestly, I'm not sure where you can find mission definitions. I haven't worked with those before.
> 
> For the cookie reauth, there are no placeholders in the url, just do a GET request using the cookies obtained from the initial auth.

Thx, I found the way to use cookie to reauthorize at https://github.com/floxay/python-riot-auth

😂 
Maybe I can guess what the `mission-id` is based on the missions in the game

**Comment by musnows** [comment]
> Honestly, I'm not sure where you can find mission definitions. I haven't worked with those before.
> 
> For the cookie reauth, there are no placeholders in the url, just do a GET request using the cookies obtained from the initial auth.

Hi, just ask for my bot-user.Will you `be banned` from fetching `daily_shop` with this API ?

Many of them are worried about it.

**Comment by techchrism** [comment]
> Hi, just ask for my bot-user.Will you `be banned` from fetching `daily_shop` with this API ?
> 
> Many of them are worried about it.

I don't have any authority but I haven't heard of any bans relating to this.
