### ISSUE TITLE
add "riot-geo" region endpoint

### ISSUE THREAD

**Issue by thedtvn** [techchrism/valorant-api-docs#15]
![image](https://user-images.githubusercontent.com/80153297/195964542-497d0083-13d5-4183-acce-81fd1ef8a036.png)
i can use my acc country at [RSO_GetPlayerInfo](https://github.com/techchrism/valorant-api-docs/blob/trunk/docs/Riot%20Auth/GET%20RSO_GetPlayerInfo.md)
and use `country` to get country code as iso3 then get country region use api
`https://restcountries.com/v3.1/alpha/{country code}`
![image](https://user-images.githubusercontent.com/80153297/195964571-f6d85e10-69e8-478e-9401-edc002f39235.png)

**Comment by thedtvn** [comment]
* this is usa acc and i am at vn

**Comment by thedtvn** [comment]
* edit this doc

**Comment by techchrism** [comment]
This method, while innovative, seems a bit sketchy.
For example, using the region data for [Brazil](https://restcountries.com/v3.1/name/brazil) results in the json `region: "Americas",
subregion: "South America"`

**Comment by thedtvn** [comment]
> This method, while innovative, seems a bit sketchy. For example, using the region data for [Brazil](https://restcountries.com/v3.1/name/brazil) results in the json `region: "Americas", subregion: "South America"`

ye

**Comment by thedtvn** [comment]
> This method, while innovative, seems a bit sketchy. For example, using the region data for [Brazil](https://restcountries.com/v3.1/name/brazil) results in the json `region: "Americas", subregion: "South America"`

@techchrism i see some one  use this api
to get Region
```js
const req = await fetch("https://riot-geo.pas.si.riotgames.com/pas/v1/product/valorant", {
        method: "PUT",
        headers: {
            'Content-Type': 'application/json',
            'Authorization': "Bearer " + user.auth.rso
        },
        body: JSON.stringify({
            'id_token': user.auth.idt,
        })
    });
```

**Comment by techchrism** [comment]
Thanks for bringing this to my attention, I'll check it out when I have the time

**Comment by thedtvn** [comment]
@techchrism if use riot-geo pls edit https://github.com/techchrism/valorant-api-docs/blob/trunk/docs/Riot%20Auth/POST%20Auth%20Cookies.md
Body  to
`{"client_id":"play-valorant-web-prod","nonce":"1","redirect_uri":"https://playvalorant.com/opt_in","response_type":"token id_token", 'scope': 'account openid'}`

**Comment by techchrism** [comment]
Has something about this endpoint changed? I haven't yet had a chance to try it out.

**Comment by rrajanaditya** [comment]
still works @techchrism please add it to docs

**Comment by thedtvn** [comment]
thank is has been 1 year :)))

**Comment by techchrism** [comment]
Sorry I was pretty slow on this one but I'm glad it have it in the docs, thanks for bringing it to my attention 👍
