### ISSUE TITLE
403 Forbidden when trying to authenticate

### ISSUE THREAD

**Issue by NavisGames** [techchrism/valorant-api-docs#16]
Because i dont want to use the fix on [the old issue](https://github.com/techchrism/valorant-api-docs/issues/13),  i opend a new issue. Are there already any other fixes already? Is python the reason or generally?
anyway, here is my code:

![image](https://user-images.githubusercontent.com/83245135/198733497-35341059-7c1c-45e5-a781-eb12d42cf241.png)

weird thing is: in insomnia there is everything working fine but not on normal codes

**Comment by techchrism** [comment]
If the same request (headers, and body) works in Insomnia but not in a program, the problem is likely TLS fingerprinting. Python isn't necessarily the issue, you just need the right TLS fingerprint.

**Comment by thedtvn** [comment]
@NavisGames  pls login use and use Cookie to get that
Ex code but Use aiohttp 
```py
       async with aiohttp.ClientSession() as s:
            async with s.get("https://login.playvalorant.com/") as r:
                pass
            data = {
                'type': 'auth',
                'username': username,
                'password': password,
                "rememberDevice": True
            }
            async with s.put("https://auth.riotgames.com/api/v1/authorization", json=data, headers=self.headers_main) as r:
                out = await r.json()
                print(out)
            data = {"client_id":"play-valorant-web-prod","nonce":"1","redirect_uri":"https://playvalorant.com/opt_in","response_type":"token id_token", 'scope': 'account openid'}
            async with s.post("https://auth.riotgames.com/api/v1/authorization", json=data, headers=self.headers_main) as r:
                    out = await r.json()
                    print(out)
```
