### ISSUE TITLE
RESOURCE_NOT_FOUND

### ISSUE THREAD

**Issue by fantasywastaken** [techchrism/valorant-api-docs#17]

**Comment by techchrism** [comment]
You need to specify the PUUID of the player. See <https://github.com/techchrism/valorant-api-docs/blob/trunk/docs/Pre-Game/GET%20Pregame_GetPlayer.md>

**Comment by fantasywastaken** [comment]
If I don't enter the match, it gives this error, I solved it, but thank you anyway.
