### ISSUE TITLE
crosshair api

### ISSUE THREAD

**Issue by putotoy** [techchrism/valorant-api-docs#21]
is there any api to change or update crosshair? thanks.

**Comment by techchrism** [comment]
Yes, you can make a `PUT` request to [RiotKV_RNet_GetSettings](https://github.com/techchrism/valorant-api-docs/blob/trunk/docs/Useful%20Local/GET%20RiotKV_RNet_GetSettings.md) to change the settings (including crosshairs).
This requires a Valorant restart to take effect.
