### ISSUE TITLE
Get player stats

### ISSUE THREAD

**Issue by JoaquimCassano** [techchrism/valorant-api-docs#37]
Is there any way to get the player kills in the current match?

**Comment by techchrism** [comment]
Not with the first-party api, no. For that, you'd need something like Overwolf: https://overwolf.github.io/api/games/events/valorant

**Comment by JoaquimCassano** [comment]
From what I saw, it is for javascript. Can i use it in python?

**Comment by techchrism** [comment]
I haven't used overwolf so I'm not sure. That would be something to ask them.
