### ISSUE TITLE
Error on AresPlayerSettings with callerID

### ISSUE THREAD

**Issue by Apocorn** [techchrism/valorant-api-docs#39]
![grafik](https://github.com/techchrism/valorant-api-docs/assets/85699908/105bf72e-f2de-4159-b7b3-454b21155d26)
When trying to get the settings it just tells me that there isn't a callerID for this session. I looked into the weird swagger docs and so on and still have no idea. Any ideas on how to solve this?

**Comment by techchrism** [comment]
Yeah I'm not really sure either. I noticed this change a while back and I'll probably remove the affected endpoints soon,

**Comment by Davi-S** [comment]
Any updates on this?
