### ISSUE TITLE
Update ContractDefinitions_Fetch

### ISSUE THREAD

**Issue by Tyrannicodin** [techchrism/valorant-api-docs#4]
Riot has updated ContractDefinitions_Fetch, I have no idea what it is now but it returns 404 now.

**Comment by KyeOnDiscord** [comment]
The new url is `https://pd.ap.a.pvp.net/contract-definitions/v3/item-upgrades`

**Comment by techchrism** [comment]
Thanks for the report and the new url, now fixed 👍
