### ISSUE TITLE
Get Contracts

### ISSUE THREAD

**Issue by sgdty** [techchrism/valorant-api-docs#51]
[Get Contracts endpoint](https://valapidocs.techchrism.me/endpoint/contracts) the 'Missions' node has no data returned,it alwayse has data before.

```json
{
    "ActiveSpecialContract": "2195e89f-20ad-4e37-b46c-cf46a6715dfd",
    "Missions": [],
    "MissionMetadata": {
        "NPECompleted": true,
        "WeeklyCheckpoint": "2023-06-27T13:00:00Z"
}
```

**Comment by techchrism** [comment]
I'm unable to replicate this.

The "WeeklyCheckpoint" has an old date on it.
Are you using the latest client version? Perhaps it's looking things up based on that.

**Comment by techchrism** [comment]
I tested with an older client version and couldn't replicate the behavior.  Is this perhaps an account that hasn't been played on in a while?

I'll mark `Version`, `Subject`, `ProcessedMatches`, and `Contracts` as optional fields in the typing docs but aside from that, this is on Riot's side of things.

**Comment by techchrism** [comment]
I just noticed the JSON you posted isn't the full response. Perhaps the other fields are below the blob you posted. Can you send a full response?

**Comment by sgdty** [comment]
I tried with the lastest client version and it works now,thank you.
