### ISSUE TITLE
Issue: GET Penalties - Encounter 400 Status Code in API Request

### ISSUE THREAD

**Issue by PrakritManStudio** [techchrism/valorant-api-docs#52]
### Description
When making a GET request to the endpoint `https://pd.{shard}.a.pvp.net/restrictions/v3/penalties` with the headers `X-Riot-Entitlements-JWT` and `Authorization`, the API returns a Status Code 400.

### Steps to Reproduce
1. Use the following request:
    ```http
    GET https://pd.{shard}.a.pvp.net/restrictions/v3/penalties
    Headers:
    X-Riot-Entitlements-JWT: {entitlement token}
    Authorization: Bearer {auth token}
    ```
2. Observe the 400 Status Code in the response.

### Solution
After further investigation, it was discovered that adding the "X-Riot-ClientPlatform" header to the request resolves the issue.

### Updated Request
```http
GET https://pd.{shard}.a.pvp.net/restrictions/v3/penalties
Headers:
X-Riot-Entitlements-JWT: {entitlement token}
Authorization: Bearer {auth token}
X-Riot-ClientPlatform: {platform info}

**Comment by techchrism** [comment]
Good catch, thank you
