### ISSUE TITLE
Bug: Issue Receiving Two-Factor Authentication Email via "Auth Request"

### ISSUE THREAD

**Issue by RetherSzu** [techchrism/valorant-api-docs#54]
# Description:
I'm having a problem with the two-factor authentication process when I try to use the "Auth Request" function. Although my configuration settings seem to be correct (see below), it's interesting to note that when I log in using the Riot client, I receive the authentication code by e-mail without any problem.

# Configuration Data:
```json
{
    "type": "multifactor",
    "multifactor": {
        "email": "*********",
        "method": "email",
        "methods": [
            "email"
        ],
        "multiFactorCodeLength": 6,
        "mfaVersion": "v2"
    },
    "country": "en",
    "securityProfile": null
}
```

# Issue:
- I am not receiving the two-factor authentication email when I use the "Auth Request" option.
- The email is correctly sent and received when logging in through the Riot client.

I am seeking assistance to resolve this issue so that I can successfully receive the two-factor authentication email when using the "Auth Request" feature.

**Comment by kr1s0404** [comment]
I am having the same issue here. I have asked other developers, he told me that Riot 2FA system implemented a new Captcha system, in order to use this 2FA API, we have to bypass(?) the Captcha, but I am not sure how to do this.

**Comment by kr1s0404** [comment]
@techchrism do you have time to look into this issue?

**Comment by techchrism** [comment]
I think bypassing captchas is outside the scope of the api docs but I'll leave this issue open until I have time to update the docs with this new info.
