### ISSUE TITLE
`INVALID_HEADERS` - Bad headers used for request

### ISSUE THREAD

**Issue by gromaxbro** [techchrism/valorant-api-docs#57]
headers = {
                        "X-Riot-Entitlements-JWT": entitlement,
                        "Authorization": f"Bearer {token}"
                    }
r = requests.get(
                        f"https://pd.{progregion}.a.pvp.net/store/v1/entitlements/{puuid}/dd3bf334-87f3-40bd-b043-682a57a8dc3a", headers=headers ,timeout=20)
                    # input(r.text)
        print(r.text)
        
**token and entitlement are ok but getiing invalid header error**
        
        {
    "httpStatus": 400,
    "errorCode": "INVALID_HEADERS",
    "message": "Bad headers used for request"
}

**Comment by IkaBey** [comment]
I have the same issue

**Comment by techchrism** [comment]
A recent change has made the `X-Riot-ClientPlatform` and `X-Riot-ClientVersion` headers mandatory for a lot of requests.

You can see an example of these here: https://valapidocs.techchrism.me/endpoint/party-player

I'll update the docs shortly to reflect the changes.

**Comment by drewgallinger** [comment]
Crazy timing I was wondering why it wasn't working 🐈‍⬛
