### ISSUE TITLE
GET Storefront returning 404

### ISSUE THREAD

**Issue by raphaelruedo** [techchrism/valorant-api-docs#61]
Hello!

The `https://pd.{shard}.a.pvp.net/store/v2/storefront/{puuid}` is returning a 404 error, even with correct requests.

Request:
```bash
curl --request GET \
  --url https://pd.{shard}.a.pvp.net/store/v2/storefront/{puuid} \
  --header 'Authorization: {access_token}' \
  --header 'X-Riot-ClientPlatform: {client_platform}' \
  --header 'X-Riot-ClientVersion: {client_version}' \
  --header 'X-Riot-Entitlements-JWT: {entitlement_token}'
  ```

The 404 error started happening today, while yesterday the requests were working correctly.

**Comment by faroukbmiled** [comment]
Api now is at /v3/ and it doesn't work like this anymore, its a POST request
Not sure if anyone figured out what the POST data is yet

posting to the new endpoint with no data returns this
{
    "httpStatus": 400,
    "errorCode": "JSON_PARSE_ERROR",
    "message": "JSON decode failure"
}

so it is definitely expecting some sort of JSON as request data


EDIT:
if you pass an empty json object "{}" to it it will work as expected

**Comment by raphaelruedo** [comment]
Thank you so much, you saved Spikehub app's life haha
I did some tests and it worked perfectly with what you pointed out.

Do you know where I can follow these version changes?

**Comment by faroukbmiled** [comment]
> Thank you so much, you saved Spikehub app's life haha I did some tests and it worked perfectly with what you pointed out.
> 
> Do you know where I can follow these version changes?

Hey no problem, I was actually experimenting with the API and discovered this on my own, but seems like others beat me to it in this Discord server. I'd say its worth joining: https://discord.gg/nf25c6YYM8

**Comment by raphaelruedo** [comment]
That's awesome. I’ll definitely check out the Discord server thanks for sharing the link!

**Comment by mahelbir** [comment]
> Api now is at /v3/ and it doesn't work like this anymore, its a POST request Not sure if anyone figured out what the POST data is yet
> 
> posting to the new endpoint with no data returns this { "httpStatus": 400, "errorCode": "JSON_PARSE_ERROR", "message": "JSON decode failure" }
> 
> so it is definitely expecting some sort of JSON as request data
> 
> EDIT: if you pass an empty json object "{}" to it it will work as expected

thank you
