### ISSUE TITLE
Storefront API changed

### ISSUE THREAD

**Issue by hakivin** [techchrism/valorant-api-docs#63]
It appears that the storefront API has been updated. The new endpoint is https://pd.%s.a.pvp.net/store/v3/storefront/%s and it now requires the use of the POST method instead of GET. When I called the API, it returned a 400 error:

```
{
    "httpStatus": 400,
    "errorCode": "JSON_PARSE_ERROR",
    "message": "JSON decode failure"
}
```
I suspect the new API requires a payload body. Is there any method to find the payload body requirements?

**Comment by ikexing-cn** [comment]
Have you found a solution?
